# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffaf8939ac7e4599bea2cd5a3f8885d324cbda65f809968b35eb03df14238bdb03f94586bc82da20dec0f915d46ad3391fe3b79d80531988403739eb158f1ace

test:
  secret_key_base: 566fcdfca85fe664b081619f64a784f521b9d01a4713265eda915a827ff1a9cc4fedea1e8583f0d6f56ed14238020a137b609ad9197bd800c070d6a2cc950c3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
